### ISSUE TITLE
The basic mechanics need implementing

### ISSUE THREAD

**Issue by PixelTheKermit** [Slimegirls-Incorporated/archecrawl#1]
So we need:

- [x] #3
- [ ] The end of the game
- [x] #4
- [ ] Villages/Towns (see #4)
- [ ] Proc-gen weapons? :godmode: 
- [ ] Respawn mechanic
- [ ] Leveling up + evolution (...trees?)
- [ ] Skills
- [ ] Unlockable Passives + Skills
- [ ] Unique unlockable passives + skills for each species

**Comment by dolgovmi** [comment]
[https://tgstation13.org/wiki/Wizard](https://tgstation13.org/wiki/Wizard this page has spells you can make
