### ISSUE TITLE
Physical and magic attacks

### ISSUE THREAD

**Issue by PixelTheKermit** [Slimegirls-Incorporated/archecrawl#2]
Just as the title says, we need a lot of attack types, ranging from hitting your enemies with swords or maces, to using a flintlock pistol and cannon artilery(?), all the way to using good ol magic.
Here are some ideas:
- Probably swords made from different metals. All having their ups and downs (expect gold. Gold is too soft and too heavy.)
- Daggers (faster but less impactful than a sword)
- Maces (Blunt > Slash/Pierce)
- Spears (Range over dps? also make it do piercing instead)
- Axes + hatchets (Would they be the same as swords/daggers?)
- Special 
- Again, flintlock pistols
- Mosins
- Cannons
- Summon another musket because reloading it takes too fucking long
- The shit Queen of Hatred uses

Dump any more spell ideas in the comments

**Comment by dolgovmi** [comment]
you're a dummy

**Comment by dolgovmi** [comment]
https://tgstation13.org/wiki/Wizard#Robed_Spells cool spells
